version: '3.8'
services:
  nuxt:
    build: ./docker/nuxt
    ports:
      - 3000:3000
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/sh -c "yarn install && yarn dev"
